/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chessQuestions from "./chess_questions";
export type { chessQuestions };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ChessCompetition } from "./ChessCompetition";
export type { ChessRiddle } from "./ChessRiddle";
export type { VToken } from "./VToken";
