/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Question1 } from "./Question1";
export type { Question2 } from "./Question2";
export type { Question3 } from "./Question3";
