/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Question1__factory } from "./Question1__factory";
export { Question2__factory } from "./Question2__factory";
export { Question3__factory } from "./Question3__factory";
