/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as chessQuestions from "./chess_questions";
export * as interfaces from "./interfaces";
export { ChessCompetition__factory } from "./ChessCompetition__factory";
export { ChessRiddle__factory } from "./ChessRiddle__factory";
export { VToken__factory } from "./VToken__factory";
